services:
  backend:
    image: golang:1.14-alpine
    networks: 
      - server    
    volumes: 
      - .:/srv
    working_dir: /srv
    ports:
      - 5050:5050
    command: go run main.go
  frontend:
    # image: node:14-alpine
    networks: 
      - server    
    volumes: 
      - ./build:/client/front-end
    working_dir: /build
    ports:
      - 8080:8080
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run serve
    
  mongo:
    image: 'mongo'
    command: ["-f",  "/etc/mongo.config"]
    volumes:
      - ./.docker/mongo.config:/etc/mongo.config
      # - ./scripts/mongo-entry.sh:/usr/local/bin/mongo-entry.sh:cached
      - 'mongo:/data/db'
    ports:
      - 2701:2701
volumes:
  mongo:
networks:
  server:
    driver: bridge
