# Dockerfile References: https://docs.docker.com/engine/reference/builder/
#
# Build and bundle the Vue.js frontend SPA 
#
FROM node:14-alpine
WORKDIR /build

COPY client/front-end/package*.json ./
RUN npm install

COPY client/front-end/ .
RUN pwd
RUN npm run build
