services:
  go_api:
    build:
      context: .
      dockerfile: Dockerfile
      # target: env
    # command: ["go", "run", "main.go"]
    container_name: go_rest_api
    ports:
      - 8080:8080
      - 5050:5050
    volumes:
      - ./:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/app_development
      - PORT=5050
    security_opt:
      - "seccomp:unconfined" # Extra option to allow debugging.
    cap_add:
      - SYS_PTRACE # Recommended option for debugging only.
  mongo:
    image: 'mongo'
    command: ["-f",  "/etc/mongo.config"]
    volumes:
      - ./.docker/mongo.config:/etc/mongo.config
      # - ./scripts/mongo-entry.sh:/usr/local/bin/mongo-entry.sh:cached
      - 'mongo:/data/db'
    ports:
      - 2701:2701
volumes:
  mongo:
